version: "3.9"
services:
  intro_container:
    build: .
    container_name: intro_container
    image: teochenglim/intro_container:latest
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    restart: unless-stopped