apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: intro-container
  name: intro-container
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: intro-container
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: intro-container
    spec:
      containers:
        - env:
            - name: UVICORN_HOST
              value: 0.0.0.0
            - name: UVICORN_PORT
              value: "8000"
          image: teochenglim/intro_container:latest
          name: intro-container
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
